version: "3.5"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - static:/frontend/build

  nginx:
    volumes:
      - static:/usr/share/nginx/html
      - ./frontend/build:/usr/share/nginx/html/
      - ./sites/pyroquinn.com/public_html:/usr/share/nginx/pyroquinn.com/public_html
      - ./sites/kelderro.nl/public_html:/usr/share/nginx/kelderro.nl/public_html
      - ./webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webserver/nginx/pyroquinn.com.conf:/etc/nginx/sites-enabled/pyroquinn.com.conf
      - ./webserver/nginx/kelderro.nl.conf:/etc/nginx/sites-enabled/kelderro.nl.conf
      - ./webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
      - ./webserver/nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

volumes:
  static:
